language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sharecoffee-addon' ]; then cd .. && eval "mv $currentfolder generator-sharecoffee-addon" && cd generator-sharecoffee-addon; fi

